"""Writes ASSET_SOURCES.md from the asset manifest and the credits recorded at download time.

    python3 scripts/assets/sources_md.py

Inputs: scripts/assets/sources.json (what we use and why), .cache/assets-src/credits.json
(authors, source pages, licence — written by fetch.py), public/assets/models/models.json.
Everything third-party here is CC0 1.0: no attribution is required, it is given anyway.
"""

import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SPEC = json.load(open(os.path.join(ROOT, "scripts", "assets", "sources.json")))
CREDITS_PATH = os.path.join(ROOT, ".cache", "assets-src", "credits.json")
CREDITS = json.load(open(CREDITS_PATH)) if os.path.exists(CREDITS_PATH) else {}


def row(name, use):
    c = CREDITS.get(name, {})
    title = c.get("title", name)
    authors = ", ".join(c.get("authors", [])) or "—"
    src = c.get("source") or (f"https://ambientcg.com/a/{name}" if name[:1].isupper() else f"https://polyhaven.com/a/{name}")
    lic = c.get("license", "CC0 1.0")
    return f"| {title} | {use} | {authors} | {src} | {lic} |"


def table(section):
    lines = ["| Asset | Used for | Creator | Source | Licence |", "| --- | --- | --- | --- | --- |"]
    for name, v in SPEC.get(section, {}).items():
        lines.append(row(name, v.get("use", "")))
    return "\n".join(lines)


out = f"""# Asset sources

Every third-party asset in this project, where it came from and its licence. All of it is
**CC0 1.0** (public domain dedication, https://creativecommons.org/publicdomain/zero/1.0/):
nothing here requires attribution to ship, and credit is given anyway.

This file is generated by `scripts/assets/sources_md.py` from `scripts/assets/sources.json`
and the credits recorded when `scripts/assets/fetch.py` downloaded each asset. Sources live in
`.cache/assets-src` (not committed); the build scripts write the optimised files under
`public/assets`.

## Skies and image-based lighting

Processed by `scripts/assets/build_env.py` into `public/assets/env` (sun removed from the
photograph and re-added as a light; stored as linear radiance in WebP).

{table("hdris")}

## Surface textures

Built by `scripts/assets/build_textures.py` into `public/assets/tex/<id>/{{color,normal,arm}}_<px>.webp`
at true scale (each set records the metres it covers). Composites — pavers, large-format
porcelain, shingles — are cut from these scans; the slate veneer of the stone base is graded from
Castle Wall Slates; the black granite is graded from a pale one.

### Poly Haven

{table("polyhaven_textures")}

### ambientCG

{table("ambientcg_textures")}

## Models

Packed by `scripts/assets/build_models.mjs` (gltf-transform: welded, lightly simplified,
meshopt-compressed, WebP textures) into `public/assets/models`.

{table("polyhaven_models")}

## Vegetation

Poly Haven plant scans, used two ways:

- near and middle distance: real-time 3D trees built by `scripts/assets/build_trees.py` and
  `build_trees.mjs` into `public/assets/trees` — the scan's own trunk and limbs (simplified with
  meshopt) and one textured card per leaf, or, for the fir (modelled needle by needle), sprig
  cards laid from the sprig pictures in its own atlas;
- far distance: hemi-octahedral impostor atlases rendered in Blender (Cycles) by
  `scripts/assets/bake_impostors.py` and packed by `pack_impostors.py` into `public/assets/plants`;
- ground cover (grass and fern clumps in the planting beds): the scans' own geometry, instanced,
  packed by the same tree scripts.

{table("polyhaven_trees")}

## Fonts (SIL Open Font License 1.1)

Loaded with `next/font/google` and self-hosted at build time.

| Font | Designer | Source | Licence |
| --- | --- | --- | --- |
| Instrument Serif | Rodrigo Fuenzalida, Jordan Egstad | https://fonts.google.com/specimen/Instrument+Serif | OFL 1.1 |
| Archivo | Omnibus-Type | https://fonts.google.com/specimen/Archivo | OFL 1.1 |
| Geist Mono | Vercel | https://fonts.google.com/specimen/Geist+Mono | OFL 1.1 |

## Brand

| Asset | Source | Notes |
| --- | --- | --- |
| VelaBuilt monogram (`public/icon.svg`, app icons) | https://velabuilt.com/icon.svg | VelaBuilt's own mark. PNG icons are rasterised from it by `scripts/og/icons.mjs`. |
| Colour and type tokens | https://velabuilt.com (site CSS) | Warm paper, near-black ink and the champagne accent come from the studio's site. |

## Made in this project

| Asset | How |
| --- | --- |
| Architecture, kitchen joinery, steel frame and connections, ducts, garden furniture | Modelled in code from the single spec in `lib/spec.ts` and `lib/steel.ts` |
| Pavers, porcelain, shingles (new and weathered), standing-seam pan | Composited from the scans above, `scripts/assets/build_textures.py` |
| Leaf and sprig cards, bark LODs | Derived from the tree scans above, `scripts/assets/build_trees.py` and `.mjs` |
| Solar cell pattern | Generated on the device, `three/proc.ts` |
| Industry tile stills `public/previews/*.webp` | Rendered from the live scene, `scripts/og/previews.mjs` |
| Share image `public/og.jpg`, no-WebGL poster `public/poster.jpg` | Rendered from the live scene, `scripts/og/render.mjs`, `scripts/og/poster.mjs` |
| UI icons | Hand-drawn inline SVG, `components/icons.tsx` |

## Software

Open-source libraries are listed in `package.json` (three.js, React Three Fiber, drei,
postprocessing, n8ao, camera-controls, motion, zustand, zod — MIT/ISC). Asset tooling: Blender
(GPL, used offline only), glTF Transform (MIT), meshoptimizer (MIT), sharp (Apache-2.0), Pillow,
NumPy and SciPy.
"""

with open(os.path.join(ROOT, "ASSET_SOURCES.md"), "w") as f:
    f.write(out)
print("ASSET_SOURCES.md written")
